### ISSUE TITLE
[v0.2.0] Bug report and some suggestions

### ISSUE THREAD

**Issue by Rogon1256** [SemyonHoyrish/GoPlayEngine#1]
1) Scene.GetAllNodes возвращает только объекты "первого" уровня, хотелось бы иметь функцию, которая возвращает все элементарные Nodes, тоесть и дети, и детей детей и т.д.
2) Scene.FindNode должна возвращать не (BaseNodeInterface, bool), а просто BaseNodeInterface. bool излишен, так как можно написать проверку на nil.
3) В [MouseButtonType](https://github.com/SemyonHoyrish/GoPlayEngine/blob/c85551ef14d21cee92d2248b13f5889a531629a1/input/mouse.go#L25C1-L29C2) стоит поменять местами MouseButtonMiddle и MouseButtonRight даже при отсутствии практической пользы, так правильнее.
4) Зачем в [PrimitiveType](https://github.com/SemyonHoyrish/GoPlayEngine/blob/c85551ef14d21cee92d2248b13f5889a531629a1/primitive/primitive.go#L6) CirclePrimitive, если есть EllipsePrimitive?

**Comment by SemyonHoyrish** [comment]
1. Совершенно в этом не уверен, в моём понимании наличие слайса с всеми существующими нодами только усложнит задачу и указывает на неправильное использование языка. Также стоит учитывать что вам придётся различать конечный тип этих нод, так функция возвращает тип `[]BaseNodeInterface`, а это не самое приятное занятие. Я считаю, что использование переменных, разнообразных структур данных в вашей программе должно давать вам возможность удобно манипулировать объектами, а функция `GetAllNodes` оставаться более внутренней функцией движка.

2. Да, вы правы, возможно изменю это.

3. Их порядок является очень важным для внутренней работы движка. Слово "правильнее" здесь вообще не применимо. Для пользователя это три константы, так что о каком порядке, в таком контексте, вы говорите не понятно.

4. `EllipsePrimitive`, как вы могли заметить ещё не реализован, является более сложным в реализации, и возможно реализован так и не будет.
